-- 007_vivero_base_tables.sql
-- Crea las tablas base del modulo vivero
-- Sin logica compleja, sin triggers, sin checks avanzados de flujo

-- =========================================================
-- TABLA: lote_vivero
-- =========================================================
CREATE TABLE IF NOT EXISTS public.lote_vivero (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  recoleccion_id BIGINT NOT NULL,
  planta_id BIGINT NOT NULL,
  vivero_id BIGINT NOT NULL,
  responsable_id BIGINT NOT NULL,

  nombre_cientifico_snapshot TEXT NOT NULL,
  nombre_comercial_snapshot TEXT NOT NULL,
  tipo_material_snapshot public.tipo_material_origen NOT NULL,

  fecha_inicio DATE NOT NULL,

  cantidad_inicial_en_proceso NUMERIC NOT NULL,
  unidad_medida_inicial public.unidad_medida NOT NULL,

  plantas_vivas_iniciales INTEGER NULL,
  saldo_vivo_actual INTEGER NULL,

  subetapa_actual public.subetapa_adaptabilidad NULL,
  estado_lote public.estado_lote_vivero NOT NULL DEFAULT 'ACTIVO',
  motivo_cierre public.motivo_cierre_lote NULL,

  codigo_trazabilidad TEXT NOT NULL UNIQUE,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_lote_vivero_recoleccion
    FOREIGN KEY (recoleccion_id)
    REFERENCES public.recoleccion (id),

  CONSTRAINT fk_lote_vivero_planta
    FOREIGN KEY (planta_id)
    REFERENCES public.planta (id),

  CONSTRAINT fk_lote_vivero_vivero
    FOREIGN KEY (vivero_id)
    REFERENCES public.vivero (id),

  CONSTRAINT fk_lote_vivero_responsable
    FOREIGN KEY (responsable_id)
    REFERENCES public.usuario (id)
);

-- =========================================================
-- TABLA: evento_lote_vivero
-- =========================================================
CREATE TABLE IF NOT EXISTS public.evento_lote_vivero (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  lote_id BIGINT NOT NULL,
  tipo_evento public.tipo_evento_vivero NOT NULL,
  fecha_evento DATE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  responsable_id BIGINT NOT NULL,

  cantidad_afectada NUMERIC NULL,
  unidad_medida_evento public.unidad_medida NULL,

  causa_merma public.causa_merma_vivero NULL,
  destino_tipo public.destino_tipo_vivero NULL,
  destino_referencia TEXT NULL,
  comunidad_destino_id BIGINT NULL,

  subetapa_destino public.subetapa_adaptabilidad NULL,

  saldo_vivo_antes INTEGER NULL,
  saldo_vivo_despues INTEGER NULL,

  motivo_cierre_calculado public.motivo_cierre_lote NULL,
  ref_evento_trigger_id BIGINT NULL,

  metadata_blockchain JSONB NULL,
  observaciones TEXT NULL,

  CONSTRAINT fk_evento_lote_vivero_lote
    FOREIGN KEY (lote_id)
    REFERENCES public.lote_vivero (id),

  CONSTRAINT fk_evento_lote_vivero_responsable
    FOREIGN KEY (responsable_id)
    REFERENCES public.usuario (id),

  CONSTRAINT fk_evento_lote_vivero_comunidad_destino
    FOREIGN KEY (comunidad_destino_id)
    REFERENCES public.division_administrativa (id),

  CONSTRAINT fk_evento_lote_vivero_ref_evento_trigger
    FOREIGN KEY (ref_evento_trigger_id)
    REFERENCES public.evento_lote_vivero (id)
);

-- PRUENAS MINIMAS
-- Revisar estructura
SELECT column_name, data_type, udt_name, is_nullable
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name IN ('lote_vivero', 'evento_lote_vivero')
ORDER BY table_name, ordinal_position;

-- Revisar FKs
SELECT
  tc.table_name,
  kcu.column_name,
  ccu.table_name AS foreign_table_name,
  ccu.column_name AS foreign_column_name,
  tc.constraint_name
FROM information_schema.table_constraints AS tc
JOIN information_schema.key_column_usage AS kcu
  ON tc.constraint_name = kcu.constraint_name
JOIN information_schema.constraint_column_usage AS ccu
  ON ccu.constraint_name = tc.constraint_name
WHERE tc.constraint_type = 'FOREIGN KEY'
  AND tc.table_schema = 'public'
  AND tc.table_name IN ('lote_vivero', 'evento_lote_vivero')
ORDER BY tc.table_name, tc.constraint_name;