-- 014_recoleccion_historial.sql
-- Objetivo:
-- - Crear infraestructura DB para historial append-only del ciclo de vida de Recoleccion
-- - Separar eventos administrativos de public.recoleccion_movimiento, que sigue siendo ledger inventariable
-- - Preparar borrado logico de borradores sin implementar aun escritura desde backend
--
-- Nota:
-- - Esta migracion crea estructura. No registra eventos historicos por si sola.
-- - El historial es append-only: se permite INSERT; se bloquea UPDATE, DELETE y TRUNCATE.

DO $$
BEGIN
  IF to_regclass('public.recoleccion') IS NULL THEN
    RAISE EXCEPTION
      'No existe public.recoleccion. Esta migracion requiere el esquema base de Recoleccion.';
  END IF;

  IF to_regclass('public.usuario') IS NULL THEN
    RAISE EXCEPTION
      'No existe public.usuario. Esta migracion requiere el esquema base de Usuario.';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'estado_registro_recoleccion'
      AND n.nspname = 'public'
  ) THEN
    RAISE EXCEPTION
      'No existe public.estado_registro_recoleccion. Esta migracion requiere el enum de estados de Recoleccion.';
  END IF;
END;
$$;

-- =========================================================
-- RECOLECCION: soporte para borrado logico
-- =========================================================

ALTER TABLE public.recoleccion
  ADD COLUMN IF NOT EXISTS eliminado_en TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS eliminado_por_usuario_id BIGINT,
  ADD COLUMN IF NOT EXISTS motivo_eliminacion TEXT;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'fk_recoleccion_eliminado_por_usuario'
      AND conrelid = 'public.recoleccion'::regclass
  ) THEN
    ALTER TABLE public.recoleccion
      ADD CONSTRAINT fk_recoleccion_eliminado_por_usuario
      FOREIGN KEY (eliminado_por_usuario_id)
      REFERENCES public.usuario (id)
      ON DELETE SET NULL;
  END IF;
END;
$$;

CREATE INDEX IF NOT EXISTS idx_recoleccion_eliminado_en
  ON public.recoleccion (eliminado_en);

COMMENT ON COLUMN public.recoleccion.eliminado_en
  IS 'Marca temporal de borrado logico. No implica eliminacion fisica del registro.';

COMMENT ON COLUMN public.recoleccion.eliminado_por_usuario_id
  IS 'Usuario que ejecuta el borrado logico de la recoleccion.';

COMMENT ON COLUMN public.recoleccion.motivo_eliminacion
  IS 'Motivo opcional del borrado logico de la recoleccion.';

-- =========================================================
-- ENUM: tipo_historial_recoleccion
-- =========================================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'tipo_historial_recoleccion'
      AND n.nspname = 'public'
  ) THEN
    CREATE TYPE public.tipo_historial_recoleccion AS ENUM (
      'BORRADOR_CREADO',
      'SOLICITUD_VALIDACION',
      'VALIDACION_APROBADA',
      'VALIDACION_RECHAZADA',
      'BORRADOR_ELIMINADO'
    );
  END IF;
END;
$$;

-- Si el enum ya existia incompleto, estas sentencias agregan los valores faltantes.
ALTER TYPE public.tipo_historial_recoleccion
  ADD VALUE IF NOT EXISTS 'BORRADOR_CREADO';

ALTER TYPE public.tipo_historial_recoleccion
  ADD VALUE IF NOT EXISTS 'SOLICITUD_VALIDACION';

ALTER TYPE public.tipo_historial_recoleccion
  ADD VALUE IF NOT EXISTS 'VALIDACION_APROBADA';

ALTER TYPE public.tipo_historial_recoleccion
  ADD VALUE IF NOT EXISTS 'VALIDACION_RECHAZADA';

ALTER TYPE public.tipo_historial_recoleccion
  ADD VALUE IF NOT EXISTS 'BORRADOR_ELIMINADO';

-- =========================================================
-- TABLA: recoleccion_historial
-- =========================================================

CREATE TABLE IF NOT EXISTS public.recoleccion_historial (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recoleccion_id BIGINT NOT NULL,
  tipo_historial public.tipo_historial_recoleccion NOT NULL,
  estado_origen public.estado_registro_recoleccion,
  estado_destino public.estado_registro_recoleccion,
  observaciones TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  actor_user_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_recoleccion_historial_recoleccion
    FOREIGN KEY (recoleccion_id)
    REFERENCES public.recoleccion (id)
    ON DELETE RESTRICT,

  CONSTRAINT fk_recoleccion_historial_actor
    FOREIGN KEY (actor_user_id)
    REFERENCES public.usuario (id)
    ON DELETE SET NULL,

  CONSTRAINT chk_recoleccion_historial_metadata_object
    CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX IF NOT EXISTS idx_recoleccion_historial_recoleccion_id
  ON public.recoleccion_historial (recoleccion_id);

CREATE INDEX IF NOT EXISTS idx_recoleccion_historial_recoleccion_created_at
  ON public.recoleccion_historial (recoleccion_id, created_at);

CREATE INDEX IF NOT EXISTS idx_recoleccion_historial_created_at
  ON public.recoleccion_historial (created_at);

CREATE INDEX IF NOT EXISTS idx_recoleccion_historial_tipo
  ON public.recoleccion_historial (tipo_historial);

CREATE INDEX IF NOT EXISTS idx_recoleccion_historial_actor_user_id
  ON public.recoleccion_historial (actor_user_id);

COMMENT ON TABLE public.recoleccion_historial
  IS 'Historial append-only del ciclo de vida del registro de recoleccion. No registra movimientos de saldo.';

COMMENT ON COLUMN public.recoleccion_historial.recoleccion_id
  IS 'Recoleccion sobre la que ocurre el evento de ciclo de vida.';

COMMENT ON COLUMN public.recoleccion_historial.tipo_historial
  IS 'Evento administrativo de ciclo de vida. No se usa para consumos, saldos ni movimientos inventariables.';

COMMENT ON COLUMN public.recoleccion_historial.estado_origen
  IS 'Estado de registro antes del evento, cuando aplique.';

COMMENT ON COLUMN public.recoleccion_historial.estado_destino
  IS 'Estado de registro despues del evento, cuando aplique.';

COMMENT ON COLUMN public.recoleccion_historial.observaciones
  IS 'Texto libre asociado al evento, por ejemplo motivo de rechazo o eliminacion.';

COMMENT ON COLUMN public.recoleccion_historial.metadata
  IS 'Datos adicionales del evento, sin reemplazar columnas estructuradas.';

COMMENT ON COLUMN public.recoleccion_historial.actor_user_id
  IS 'Usuario que ejecuta el evento. Puede ser null para eventos automaticos o migraciones.';

COMMENT ON COLUMN public.recoleccion_historial.created_at
  IS 'Momento en que se registro el evento historico.';

-- =========================================================
-- APPEND-ONLY: bloquear mutaciones del historial
-- =========================================================

CREATE OR REPLACE FUNCTION public.fn_recoleccion_historial_prevent_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION
    'public.recoleccion_historial es append-only: no se permite %, solo INSERT.',
    TG_OP;
END;
$$;

DROP TRIGGER IF EXISTS trg_recoleccion_historial_prevent_mutation
  ON public.recoleccion_historial;

CREATE TRIGGER trg_recoleccion_historial_prevent_mutation
BEFORE UPDATE OR DELETE OR TRUNCATE ON public.recoleccion_historial
FOR EACH STATEMENT
EXECUTE FUNCTION public.fn_recoleccion_historial_prevent_mutation();

GRANT INSERT, SELECT ON TABLE public.recoleccion_historial TO service_role;

DO $$
BEGIN
  IF to_regclass('public.recoleccion_historial_id_seq') IS NOT NULL THEN
    GRANT USAGE, SELECT ON SEQUENCE public.recoleccion_historial_id_seq TO service_role;
  END IF;
END;
$$;

NOTIFY pgrst, 'reload schema';
