-- 024_vivero_asignacion_subcampania.sql
-- Crea la tabla ASIGNACION_VIVERO_SUBCAMPANIA: reserva logica de lotes de vivero
-- hacia subcampanas de M3. Incluye enums, indices y trigger de transicion de estado.

-- =====================================================================
-- 1. Enums
-- =====================================================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'proposito_asignacion'
      AND n.nspname = 'public'
  ) THEN
    CREATE TYPE public.proposito_asignacion AS ENUM (
      'PLANTACION_INICIAL',
      'REPOSICION'
    );
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'estado_asignacion_vivero'
      AND n.nspname = 'public'
  ) THEN
    -- AFECTADA_POR_MERMA se omite del enum; se expone como badge derivado
    -- cuando cantidad_mermada > 0. Ver tarea 02 y addendum seccion 11.2.
    CREATE TYPE public.estado_asignacion_vivero AS ENUM (
      'ACTIVA',
      'AGOTADA',
      'DEVUELTA'
    );
  END IF;
END $$;

-- =====================================================================
-- 2. Tabla asignacion_vivero_subcampania
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.asignacion_vivero_subcampania (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  subcampania_id BIGINT NOT NULL,
  lote_vivero_id BIGINT NOT NULL,
  proposito      public.proposito_asignacion      NOT NULL,
  estado         public.estado_asignacion_vivero  NOT NULL DEFAULT 'ACTIVA',

  cantidad_asignada  INT NOT NULL,
  cantidad_consumida INT NOT NULL DEFAULT 0,
  cantidad_devuelta  INT NOT NULL DEFAULT 0,
  cantidad_mermada   INT NOT NULL DEFAULT 0,

  -- Columna derivada: saldo disponible para consumo dentro de esta asignacion.
  -- GENERATED ALWAYS AS STORED: el motor la mantiene; no se puede escribir directamente.
  saldo_asignado_disponible INT GENERATED ALWAYS AS (
    cantidad_asignada - cantidad_consumida - cantidad_devuelta - cantidad_mermada
  ) STORED,

  usuario_asignacion_id BIGINT NOT NULL,
  fecha_asignacion      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT asignacion_vivero_subcampania_lote_fk
    FOREIGN KEY (lote_vivero_id)
    REFERENCES public.lote_vivero (id),

  CONSTRAINT asignacion_vivero_subcampania_usuario_fk
    FOREIGN KEY (usuario_asignacion_id)
    REFERENCES public.usuario (id),

  CONSTRAINT asignacion_cantidad_asignada_positiva_chk
    CHECK (cantidad_asignada > 0),

  CONSTRAINT asignacion_cantidad_consumida_no_negativa_chk
    CHECK (cantidad_consumida >= 0),

  CONSTRAINT asignacion_cantidad_devuelta_no_negativa_chk
    CHECK (cantidad_devuelta >= 0),

  CONSTRAINT asignacion_cantidad_mermada_no_negativa_chk
    CHECK (cantidad_mermada >= 0),

  -- Impide que consumido + devuelto + mermado supere lo asignado
  CONSTRAINT asignacion_consistencia_saldos_chk
    CHECK (cantidad_asignada >= cantidad_consumida + cantidad_devuelta + cantidad_mermada)
);

-- FK pendiente a SUBCAMPANIA (Modulo 3) — se materializa cuando exista esa tabla en BD
COMMENT ON COLUMN public.asignacion_vivero_subcampania.subcampania_id
  IS 'FK pendiente a SUBCAMPANIA cuando se cree Modulo 3.';

-- =====================================================================
-- 3. Indices
-- =====================================================================

-- Consultas de stock disponible por lote (solo asignaciones activas)
CREATE INDEX IF NOT EXISTS asignacion_vivero_subcampania_lote_idx
  ON public.asignacion_vivero_subcampania (lote_vivero_id)
  WHERE estado = 'ACTIVA';

-- Consultas por subcampana (patron M3 → M2)
CREATE INDEX IF NOT EXISTS asignacion_vivero_subcampania_subcampania_idx
  ON public.asignacion_vivero_subcampania (subcampania_id);

-- Soporte FIFO para politica de mermas (tarea 04): menor fecha_asignacion primero
CREATE INDEX IF NOT EXISTS asignacion_vivero_subcampania_fecha_fifo_idx
  ON public.asignacion_vivero_subcampania (lote_vivero_id, fecha_asignacion)
  WHERE estado = 'ACTIVA';

-- =====================================================================
-- 4. Trigger de transicion de estado
-- =====================================================================

-- Nota: saldo_asignado_disponible es GENERATED ALWAYS STORED. En Postgres, las columnas
-- GENERATED se computan DESPUES de los BEFORE triggers, por lo que dentro del trigger
-- ese campo es NULL. El trigger recalcula el saldo a mano con las cuatro columnas base.
CREATE OR REPLACE FUNCTION public.asignacion_vivero_subcampania_actualizar_estado()
RETURNS TRIGGER
LANGUAGE plpgsql AS $$
DECLARE
  v_saldo INT;
BEGIN
  v_saldo := NEW.cantidad_asignada
           - NEW.cantidad_consumida
           - NEW.cantidad_devuelta
           - NEW.cantidad_mermada;

  NEW.updated_at := NOW();

  IF v_saldo = 0
     AND NEW.cantidad_consumida = 0
     AND NEW.cantidad_devuelta = NEW.cantidad_asignada THEN
    NEW.estado := 'DEVUELTA';
  ELSIF v_saldo = 0 THEN
    NEW.estado := 'AGOTADA';
  ELSE
    NEW.estado := 'ACTIVA';
  END IF;

  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS asignacion_vivero_subcampania_estado_trg
  ON public.asignacion_vivero_subcampania;

CREATE TRIGGER asignacion_vivero_subcampania_estado_trg
  BEFORE INSERT OR UPDATE OF cantidad_consumida, cantidad_devuelta, cantidad_mermada
  ON public.asignacion_vivero_subcampania
  FOR EACH ROW EXECUTE FUNCTION public.asignacion_vivero_subcampania_actualizar_estado();
