-- 028_m3_campania.sql
-- Modulo 3 (Plantacion) — base 2/6: tabla CAMPANIA y puente CAMPANIA_ORGANIZACION.
-- Origen: tareas/modulo-2-integracion-modulo-3/11_db_modelado_m3_base.md (seccion 2.3).
-- Depende de: 027_m3_postgis_y_enums.sql.
-- La vista campania_estado (seccion 2.7) se crea al final de 029, porque
-- depende de public.subcampania.
-- Idempotente.

-- =====================================================================
-- 0. Tabla maestra ORGANIZACION (placeholder defensivo)
-- =====================================================================
-- La tabla ORGANIZACION corresponde al modulo General y todavia no esta
-- materializada en este repo de migraciones. Se crea aqui como placeholder
-- con columnas minimas para que el FK de CAMPANIA_ORGANIZACION resuelva.
-- Cuando el modulo General defina la tabla definitiva, esta entrada debe
-- migrarse / ampliarse, no recrearse.

CREATE TABLE IF NOT EXISTS public.organizacion (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre      TEXT NOT NULL,
  activo      BOOLEAN NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.organizacion IS
  'Placeholder modulo General. Reemplazar/ampliar cuando el modulo General defina su esquema.';

-- =====================================================================
-- 1. Tabla CAMPANIA
-- =====================================================================
-- Contenedor estrategico. No persiste estado: el estado es derivado via vista
-- campania_estado (invariante CLAUDE.md / tarea 10).

CREATE TABLE IF NOT EXISTS public.campania (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre                TEXT NOT NULL UNIQUE,
  descripcion           TEXT,
  fecha_estimada_inicio DATE,
  fecha_estimada_fin    DATE,

  -- Formato sugerido: 'CMP-YYYY-NNN'
  codigo_trazabilidad   TEXT NOT NULL UNIQUE,

  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by            BIGINT NOT NULL,
  updated_by            BIGINT NOT NULL,
  deleted_at            TIMESTAMPTZ,
  deleted_by            BIGINT,
  metadata_blockchain   JSONB,

  CONSTRAINT campania_created_by_fk
    FOREIGN KEY (created_by) REFERENCES public.usuario (id),
  CONSTRAINT campania_updated_by_fk
    FOREIGN KEY (updated_by) REFERENCES public.usuario (id),
  CONSTRAINT campania_deleted_by_fk
    FOREIGN KEY (deleted_by) REFERENCES public.usuario (id)
);

COMMENT ON TABLE public.campania IS
  'Contenedor estrategico de subcampanias. No persiste estado: el estado es derivado via vista campania_estado.';

-- =====================================================================
-- 2. Tabla puente CAMPANIA_ORGANIZACION (N:M con organizacion)
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.campania_organizacion (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campania_id     BIGINT NOT NULL,
  organizacion_id BIGINT NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by      BIGINT NOT NULL,

  CONSTRAINT campania_organizacion_campania_fk
    FOREIGN KEY (campania_id)
    REFERENCES public.campania (id)
    ON DELETE CASCADE,

  CONSTRAINT campania_organizacion_organizacion_fk
    FOREIGN KEY (organizacion_id)
    REFERENCES public.organizacion (id),

  CONSTRAINT campania_organizacion_created_by_fk
    FOREIGN KEY (created_by)
    REFERENCES public.usuario (id),

  CONSTRAINT campania_organizacion_uq
    UNIQUE (campania_id, organizacion_id)
);

-- =====================================================================
-- Nota: la vista campania_estado (seccion 2.7 del spec) se crea en 029,
-- porque depende de public.subcampania.
-- =====================================================================
