-- 029_m3_subcampania.sql
-- Modulo 3 (Plantacion) — base 3/6: tablas SUBCAMPANIA y SUBCAMPANIA_EQUIPO,
-- mas la vista campania_estado (que depende de SUBCAMPANIA y por eso vive aqui).
-- Origen: tareas/modulo-2-integracion-modulo-3/11_db_modelado_m3_base.md (seccion 2.4 + 2.7).
-- Depende de: 027 (enums + postgis) y 028 (campania).
-- Idempotente.

-- =====================================================================
-- 1. Tabla SUBCAMPANIA
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.subcampania (
  id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campania_id                 BIGINT NOT NULL,
  nombre                      TEXT NOT NULL,
  descripcion                 TEXT,
  tipo                        public.tipo_subcampania NOT NULL,
  estado                      public.estado_subcampania NOT NULL DEFAULT 'BORRADOR',
  fase_mantenimiento          public.fase_mantenimiento_subcampania NOT NULL DEFAULT 'NO_APLICA',

  zona_id                     BIGINT NOT NULL,
  poligono_geom               geometry(Polygon, 4326),
  area_hectareas              NUMERIC(12,4),
  meta_total_arboles          INT NOT NULL CHECK (meta_total_arboles > 0),

  fecha_estimada_inicio       DATE,
  fecha_estimada_fin          DATE,
  fecha_cierre_operativo      TIMESTAMPTZ,
  fecha_fin_mantenimiento     DATE,

  motivo_cierre_parcial       public.motivo_cierre_parcial,
  observaciones_cierre        TEXT,

  tolerancia_gps_metros       INT NOT NULL DEFAULT 50 CHECK (tolerancia_gps_metros > 0),

  -- Snapshots inmutables congelados al activar (seteo via handler).
  nombre_zona_snapshot            TEXT,
  nombre_coordinador_snapshot     TEXT,
  nombres_organizaciones_snapshot TEXT[],

  -- Formato sugerido: 'SUB-NNN-CMP-YYYY-NNN'
  codigo_trazabilidad         TEXT NOT NULL UNIQUE,

  -- Contadores materializados (mantenidos por trigger en tarea 12 — arrancan en 0).
  total_plantado_inicial      INT NOT NULL DEFAULT 0,
  total_repuesto              INT NOT NULL DEFAULT 0,
  total_muerto_acumulado      INT NOT NULL DEFAULT 0,
  saldo_vivo_actual           INT GENERATED ALWAYS AS (
    total_plantado_inicial + total_repuesto - total_muerto_acumulado
  ) STORED,

  created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by                  BIGINT NOT NULL,
  updated_by                  BIGINT NOT NULL,
  deleted_at                  TIMESTAMPTZ,
  deleted_by                  BIGINT,
  metadata_blockchain         JSONB,

  CONSTRAINT subcampania_campania_fk
    FOREIGN KEY (campania_id) REFERENCES public.campania (id),

  CONSTRAINT subcampania_zona_fk
    FOREIGN KEY (zona_id) REFERENCES public.division_administrativa (id),

  CONSTRAINT subcampania_created_by_fk
    FOREIGN KEY (created_by) REFERENCES public.usuario (id),
  CONSTRAINT subcampania_updated_by_fk
    FOREIGN KEY (updated_by) REFERENCES public.usuario (id),
  CONSTRAINT subcampania_deleted_by_fk
    FOREIGN KEY (deleted_by) REFERENCES public.usuario (id),

  -- Activar requiere poligono.
  CONSTRAINT subcampania_activacion_poligono_chk
    CHECK (estado = 'BORRADOR' OR poligono_geom IS NOT NULL),

  -- Cierre (COMPLETADA o FINALIZADA_PARCIAL) requiere ambas fechas.
  CONSTRAINT subcampania_cierre_chk
    CHECK (
      estado NOT IN ('COMPLETADA', 'FINALIZADA_PARCIAL')
      OR (fecha_cierre_operativo IS NOT NULL AND fecha_fin_mantenimiento IS NOT NULL)
    ),

  -- Cierre parcial requiere motivo.
  CONSTRAINT subcampania_cierre_parcial_motivo_chk
    CHECK (
      estado <> 'FINALIZADA_PARCIAL'
      OR motivo_cierre_parcial IS NOT NULL
    )
);

COMMENT ON COLUMN public.subcampania.poligono_geom IS
  'Poligono certificable en WGS84. Obligatorio para activar.';

COMMENT ON COLUMN public.subcampania.fase_mantenimiento IS
  'Persistida con default NO_APLICA. Pasa a MANTENIMIENTO_ACTIVO al cerrar y a MONITOREO_HISTORICO 3 anos despues via job nocturno (pendiente).';

COMMENT ON COLUMN public.subcampania.total_plantado_inicial IS
  'Contador materializado. Mantenido por trigger (tarea 12). Arranca en 0.';
COMMENT ON COLUMN public.subcampania.total_repuesto IS
  'Contador materializado. Mantenido por trigger (tarea 12). Arranca en 0.';
COMMENT ON COLUMN public.subcampania.total_muerto_acumulado IS
  'Contador materializado. Mantenido por trigger (tarea 12). Arranca en 0.';

CREATE INDEX IF NOT EXISTS subcampania_campania_idx
  ON public.subcampania (campania_id);

CREATE INDEX IF NOT EXISTS subcampania_zona_idx
  ON public.subcampania (zona_id);

CREATE INDEX IF NOT EXISTS subcampania_estado_idx
  ON public.subcampania (estado)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS subcampania_poligono_gix
  ON public.subcampania
  USING gist (poligono_geom);

-- =====================================================================
-- 2. Tabla SUBCAMPANIA_EQUIPO
-- =====================================================================
-- La identidad del coordinador no vive en una columna coordinador_id en
-- SUBCAMPANIA: se obtiene como la fila con rol = 'COORDINADOR'. La unicidad
-- la garantiza el unique index parcial mas abajo (decision cerrada en tarea 10).

CREATE TABLE IF NOT EXISTS public.subcampania_equipo (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subcampania_id  BIGINT NOT NULL,
  usuario_id      BIGINT NOT NULL,
  rol             public.rol_en_subcampania NOT NULL,
  agregado_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  agregado_by     BIGINT NOT NULL,

  CONSTRAINT subcampania_equipo_subcampania_fk
    FOREIGN KEY (subcampania_id)
    REFERENCES public.subcampania (id)
    ON DELETE CASCADE,

  CONSTRAINT subcampania_equipo_usuario_fk
    FOREIGN KEY (usuario_id) REFERENCES public.usuario (id),

  CONSTRAINT subcampania_equipo_agregado_by_fk
    FOREIGN KEY (agregado_by) REFERENCES public.usuario (id),

  CONSTRAINT subcampania_equipo_uq
    UNIQUE (subcampania_id, usuario_id)
);

-- Exactamente 1 COORDINADOR por subcampania.
CREATE UNIQUE INDEX IF NOT EXISTS subcampania_equipo_un_coordinador_idx
  ON public.subcampania_equipo (subcampania_id)
  WHERE rol = 'COORDINADOR';

CREATE INDEX IF NOT EXISTS subcampania_equipo_usuario_idx
  ON public.subcampania_equipo (usuario_id);

-- =====================================================================
-- 3. Vista campania_estado (estado derivado — depende de subcampania)
-- =====================================================================
-- Definida aqui porque referencia public.subcampania.

CREATE OR REPLACE VIEW public.campania_estado AS
SELECT
  c.id AS campania_id,
  CASE
    WHEN NOT EXISTS (
      SELECT 1 FROM public.subcampania s
      WHERE s.campania_id = c.id AND s.deleted_at IS NULL
    ) THEN 'BORRADOR'
    WHEN EXISTS (
      SELECT 1 FROM public.subcampania s
      WHERE s.campania_id = c.id
        AND s.deleted_at IS NULL
        AND s.estado = 'ACTIVA'
    ) THEN 'ACTIVA'
    WHEN EXISTS (
      SELECT 1 FROM public.subcampania s
      WHERE s.campania_id = c.id
        AND s.deleted_at IS NULL
        AND s.fase_mantenimiento = 'MANTENIMIENTO_ACTIVO'
    ) THEN 'EN_MANTENIMIENTO'
    WHEN NOT EXISTS (
      SELECT 1 FROM public.subcampania s
      WHERE s.campania_id = c.id
        AND s.deleted_at IS NULL
        AND s.fase_mantenimiento <> 'MONITOREO_HISTORICO'
    ) THEN 'MONITOREO_HISTORICO'
    ELSE 'BORRADOR'
  END AS estado_derivado
FROM public.campania c;

COMMENT ON VIEW public.campania_estado IS
  'Estado de campana derivado en tiempo real desde sus subcampanias (invariante CLAUDE.md). No materializar.';
