-- 030_m3_registro_plantacion.sql
-- Modulo 3 (Plantacion) — base 4/6: tablas REGISTRO_PLANTACION,
-- REGISTRO_PLANTACION_DETALLE y REGISTRO_PLANTACION_CORESPONSABLE.
-- Origen: tareas/modulo-2-integracion-modulo-3/11_db_modelado_m3_base.md (seccion 2.5).
-- Depende de: 029 (subcampania), 024 (asignacion_vivero_subcampania),
--             007 (lote_vivero, evento_lote_vivero), 005/022 (planta).
-- Idempotente.

-- =====================================================================
-- 1. Tabla REGISTRO_PLANTACION
-- =====================================================================
-- Una fila por grupo plantado en un evento. es_reposicion separa el grupo
-- inicial del grupo de reposicion (que cuelga del grupo origen via
-- registro_plantacion_origen_id). Sin mix de especies en MVP, pero un grupo
-- puede tener detalle multi-asignacion (varios lotes/plantas de una misma
-- subcampania) — eso se modela en registro_plantacion_detalle.

CREATE TABLE IF NOT EXISTS public.registro_plantacion (
  id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subcampania_id                  BIGINT NOT NULL,
  es_reposicion                   BOOLEAN NOT NULL DEFAULT FALSE,
  registro_plantacion_origen_id   BIGINT,

  fecha_plantacion                DATE NOT NULL,
  responsable_id                  BIGINT NOT NULL,

  latitud                         NUMERIC(9,6) NOT NULL CHECK (latitud BETWEEN -90 AND 90),
  longitud                        NUMERIC(9,6) NOT NULL CHECK (longitud BETWEEN -180 AND 180),
  gps_dentro_poligono             BOOLEAN NOT NULL,
  gps_distancia_a_poligono_m      NUMERIC(10,2),

  cantidad_total_plantada         INT NOT NULL CHECK (cantidad_total_plantada > 0),
  cantidad_muerta_acumulada       INT NOT NULL DEFAULT 0 CHECK (cantidad_muerta_acumulada >= 0),
  cantidad_repuesta_acumulada     INT NOT NULL DEFAULT 0 CHECK (cantidad_repuesta_acumulada >= 0),
  saldo_vivo_grupo                INT GENERATED ALWAYS AS (
    cantidad_total_plantada + cantidad_repuesta_acumulada - cantidad_muerta_acumulada
  ) STORED,

  -- Snapshots inmutables (handler los congela al insertar).
  nombre_subcampania_snapshot     TEXT,
  nombre_zona_snapshot            TEXT,
  nombre_responsable_snapshot     TEXT,
  observaciones                   TEXT,

  -- Formato sugerido: 'PLT-NNN-SUB-NNN'
  codigo_trazabilidad             TEXT NOT NULL UNIQUE,

  created_at                      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by                      BIGINT NOT NULL,
  metadata_blockchain             JSONB,

  CONSTRAINT registro_plantacion_subcampania_fk
    FOREIGN KEY (subcampania_id) REFERENCES public.subcampania (id),

  CONSTRAINT registro_plantacion_responsable_fk
    FOREIGN KEY (responsable_id) REFERENCES public.usuario (id),

  CONSTRAINT registro_plantacion_created_by_fk
    FOREIGN KEY (created_by) REFERENCES public.usuario (id),

  CONSTRAINT registro_plantacion_origen_fk
    FOREIGN KEY (registro_plantacion_origen_id)
    REFERENCES public.registro_plantacion (id),

  -- Reposicion debe referenciar grupo origen; plantacion inicial NO.
  CONSTRAINT registro_plantacion_reposicion_origen_chk
    CHECK (
      (es_reposicion = FALSE AND registro_plantacion_origen_id IS NULL)
      OR
      (es_reposicion = TRUE  AND registro_plantacion_origen_id IS NOT NULL)
    ),

  -- Saldo vivo del grupo no negativo (defensa redundante con la generated column).
  CONSTRAINT registro_plantacion_saldo_no_negativo_chk
    CHECK (cantidad_total_plantada + cantidad_repuesta_acumulada - cantidad_muerta_acumulada >= 0)
);

COMMENT ON COLUMN public.registro_plantacion.cantidad_muerta_acumulada IS
  'Mantenido por trigger en EVENTO_PLANTACION/MORTANDAD_REPORTADA (tarea 12). Arranca en 0.';
COMMENT ON COLUMN public.registro_plantacion.cantidad_repuesta_acumulada IS
  'Mantenido por trigger en INSERT de REGISTRO_PLANTACION con es_reposicion=TRUE sobre el grupo origen (tarea 12).';

CREATE INDEX IF NOT EXISTS registro_plantacion_subcampania_idx
  ON public.registro_plantacion (subcampania_id);

CREATE INDEX IF NOT EXISTS registro_plantacion_origen_idx
  ON public.registro_plantacion (registro_plantacion_origen_id)
  WHERE es_reposicion = TRUE;

CREATE INDEX IF NOT EXISTS registro_plantacion_responsable_idx
  ON public.registro_plantacion (responsable_id);

-- =====================================================================
-- 2. Tabla REGISTRO_PLANTACION_DETALLE
-- =====================================================================
-- Linea de detalle: que asignacion/lote/planta y cuanta cantidad de cada uno
-- entro al grupo. Una fila por (registro, asignacion, planta).

CREATE TABLE IF NOT EXISTS public.registro_plantacion_detalle (
  id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  registro_plantacion_id          BIGINT NOT NULL,
  asignacion_id                   BIGINT NOT NULL,
  lote_vivero_id                  BIGINT NOT NULL,
  planta_id                       BIGINT NOT NULL,
  cantidad                        INT NOT NULL CHECK (cantidad > 0),

  nombre_cientifico_snapshot      TEXT,
  nombre_comercial_snapshot       TEXT,
  variedad_snapshot               TEXT,

  evento_lote_vivero_despacho_id  BIGINT,

  created_at                      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT registro_plantacion_detalle_registro_fk
    FOREIGN KEY (registro_plantacion_id)
    REFERENCES public.registro_plantacion (id)
    ON DELETE CASCADE,

  CONSTRAINT registro_plantacion_detalle_asignacion_fk
    FOREIGN KEY (asignacion_id)
    REFERENCES public.asignacion_vivero_subcampania (id),

  CONSTRAINT registro_plantacion_detalle_lote_fk
    FOREIGN KEY (lote_vivero_id) REFERENCES public.lote_vivero (id),

  CONSTRAINT registro_plantacion_detalle_planta_fk
    FOREIGN KEY (planta_id) REFERENCES public.planta (id),

  CONSTRAINT registro_plantacion_detalle_despacho_fk
    FOREIGN KEY (evento_lote_vivero_despacho_id)
    REFERENCES public.evento_lote_vivero (id),

  CONSTRAINT registro_plantacion_detalle_uq
    UNIQUE (registro_plantacion_id, asignacion_id, planta_id)
);

COMMENT ON COLUMN public.registro_plantacion_detalle.lote_vivero_id IS
  'Redundante con asignacion.lote_vivero_id; mantenido para queries rapidas. Debe coincidir.';

COMMENT ON COLUMN public.registro_plantacion_detalle.evento_lote_vivero_despacho_id IS
  'FK al DESPACHO automatico generado por tarea 03. NULL solo en intermedio de transaccion.';

CREATE INDEX IF NOT EXISTS registro_plantacion_detalle_lote_idx
  ON public.registro_plantacion_detalle (lote_vivero_id);

CREATE INDEX IF NOT EXISTS registro_plantacion_detalle_asignacion_idx
  ON public.registro_plantacion_detalle (asignacion_id);

-- =====================================================================
-- 3. Tabla REGISTRO_PLANTACION_CORESPONSABLE
-- =====================================================================
-- Usuarios adicionales (subset del SUBCAMPANIA_EQUIPO) que firman el registro.
-- La pertenencia al equipo la valida el handler, no la BD.

CREATE TABLE IF NOT EXISTS public.registro_plantacion_coresponsable (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  registro_plantacion_id  BIGINT NOT NULL,
  usuario_id              BIGINT NOT NULL,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT registro_plantacion_coresponsable_registro_fk
    FOREIGN KEY (registro_plantacion_id)
    REFERENCES public.registro_plantacion (id)
    ON DELETE CASCADE,

  CONSTRAINT registro_plantacion_coresponsable_usuario_fk
    FOREIGN KEY (usuario_id) REFERENCES public.usuario (id),

  CONSTRAINT registro_plantacion_coresponsable_uq
    UNIQUE (registro_plantacion_id, usuario_id)
);

COMMENT ON TABLE public.registro_plantacion_coresponsable IS
  'Co-responsables del registro. Deben ser subset del SUBCAMPANIA_EQUIPO de la subcampana (validacion en handler).';
