-- 031_m3_evento_plantacion.sql
-- Modulo 3 (Plantacion) — base 5/6: tabla unificada EVENTO_PLANTACION para
-- eventos auxiliares (mortandad, devolucion, registro de asignacion). Sigue
-- el patron de EVENTO_LOTE_VIVERO de M2.
-- Origen: tareas/modulo-2-integracion-modulo-3/11_db_modelado_m3_base.md (seccion 2.6).
-- Depende de: 029 (subcampania), 030 (registro_plantacion), 024 (asignacion).
-- Idempotente.
--
-- Nota: PLANTACION_INICIAL y REPOSICION NO van aqui. Esos viven como filas
-- en REGISTRO_PLANTACION con es_reposicion = false | true.

CREATE TABLE IF NOT EXISTS public.evento_plantacion (
  id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_evento              public.tipo_evento_plantacion NOT NULL,

  subcampania_id           BIGINT NOT NULL,
  registro_plantacion_id   BIGINT,
  asignacion_id            BIGINT,

  fecha_evento             TIMESTAMPTZ NOT NULL,
  responsable_id           BIGINT NOT NULL,
  observaciones            TEXT,

  -- MORTANDAD_REPORTADA
  cantidad_muerta_delta    INT,
  causa_mortandad          public.causa_mortandad_plantacion,
  latitud                  NUMERIC(9,6),
  longitud                 NUMERIC(9,6),

  -- DEVOLUCION_A_VIVERO
  cantidad_devuelta        INT,
  motivo_devolucion        public.motivo_devolucion_plantacion,

  -- ASIGNACION_VIVERO (registro del evento; la fuente de verdad es
  -- ASIGNACION_VIVERO_SUBCAMPANIA).
  cantidad_asignada_evento INT,

  created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by               BIGINT NOT NULL,
  metadata_blockchain      JSONB,

  CONSTRAINT evento_plantacion_subcampania_fk
    FOREIGN KEY (subcampania_id) REFERENCES public.subcampania (id),

  CONSTRAINT evento_plantacion_registro_fk
    FOREIGN KEY (registro_plantacion_id) REFERENCES public.registro_plantacion (id),

  CONSTRAINT evento_plantacion_asignacion_fk
    FOREIGN KEY (asignacion_id) REFERENCES public.asignacion_vivero_subcampania (id),

  CONSTRAINT evento_plantacion_responsable_fk
    FOREIGN KEY (responsable_id) REFERENCES public.usuario (id),

  CONSTRAINT evento_plantacion_created_by_fk
    FOREIGN KEY (created_by) REFERENCES public.usuario (id),

  -- Coherencia MORTANDAD_REPORTADA.
  CONSTRAINT evento_plantacion_mortandad_chk
    CHECK (
      tipo_evento <> 'MORTANDAD_REPORTADA'
      OR (
        cantidad_muerta_delta > 0
        AND causa_mortandad IS NOT NULL
        AND registro_plantacion_id IS NOT NULL
        AND latitud IS NOT NULL
        AND longitud IS NOT NULL
      )
    ),

  -- Coherencia DEVOLUCION_A_VIVERO.
  CONSTRAINT evento_plantacion_devolucion_chk
    CHECK (
      tipo_evento <> 'DEVOLUCION_A_VIVERO'
      OR (
        cantidad_devuelta > 0
        AND motivo_devolucion IS NOT NULL
        AND asignacion_id IS NOT NULL
      )
    ),

  -- Coherencia ASIGNACION_VIVERO.
  CONSTRAINT evento_plantacion_asignacion_chk
    CHECK (
      tipo_evento <> 'ASIGNACION_VIVERO'
      OR (
        cantidad_asignada_evento > 0
        AND asignacion_id IS NOT NULL
      )
    )
);

CREATE INDEX IF NOT EXISTS evento_plantacion_subcampania_fecha_idx
  ON public.evento_plantacion (subcampania_id, fecha_evento DESC);

CREATE INDEX IF NOT EXISTS evento_plantacion_registro_idx
  ON public.evento_plantacion (registro_plantacion_id)
  WHERE registro_plantacion_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS evento_plantacion_asignacion_idx
  ON public.evento_plantacion (asignacion_id)
  WHERE asignacion_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS evento_plantacion_tipo_fecha_idx
  ON public.evento_plantacion (tipo_evento, fecha_evento DESC);
