-- 047_m3_cancelacion_subcampania_y_plan.sql
-- Modulo 3 (Plantacion) — cierra las decisiones del 2026-07-01:
--   1. SUBCAMPANIA_HISTORIAL append-only con enum de eventos (BORRADOR_CREADO,
--      SUBCAMPANIA_ACTIVADA, SUBCAMPANIA_CANCELADA, etc.) — infra base para
--      cerrar la trazabilidad interna de la subcampania. RN-PLA-06/08/37.
--   2. SUBCAMPANIA_META_ESPECIE (plan por especie), unique (subcampania_id, planta_id)
--      con checks de porcentaje y cantidad. RN-PLA-15/16.
--   3. fn_subcampania_cancelar: RPC transaccional que ejecuta RN-PLA-37 (guard
--      total_plantado_inicial = 0, libera asignaciones activas como devolucion
--      logica y registra el evento de historial). No genera evento en M2 (RN-VIV-48).
--   4. CREATE OR REPLACE fn_vivero_reservar_stock_lote: el guard de estado ahora
--      depende del proposito. PLANTACION_INICIAL solo en ACTIVA; REPOSICION en
--      ACTIVA/COMPLETADA/FINALIZADA_PARCIAL; nunca en BORRADOR ni CANCELADA.
-- Idempotente.

-- =====================================================================
-- 0. Precondiciones
-- =====================================================================

DO $$
BEGIN
  IF to_regclass('public.subcampania') IS NULL THEN
    RAISE EXCEPTION
      'No existe public.subcampania. Aplicar 029_m3_subcampania.sql antes de esta migracion.';
  END IF;

  IF to_regclass('public.asignacion_vivero_subcampania') IS NULL THEN
    RAISE EXCEPTION
      'No existe public.asignacion_vivero_subcampania. Aplicar 024_vivero_asignacion_subcampania.sql antes de esta migracion.';
  END IF;
END $$;

-- =====================================================================
-- 1. Enum tipo_historial_subcampania
-- =====================================================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'tipo_historial_subcampania'
      AND n.nspname = 'public'
  ) THEN
    CREATE TYPE public.tipo_historial_subcampania AS ENUM (
      'BORRADOR_CREADO',
      'SUBCAMPANIA_ACTIVADA',
      'SUBCAMPANIA_COMPLETADA',
      'SUBCAMPANIA_FINALIZADA_PARCIAL',
      'SUBCAMPANIA_CANCELADA',
      'TRANSICION_A_MONITOREO_HISTORICO',
      'EQUIPO_AMPLIADO',
      'EQUIPO_REDUCIDO',
      'COORDINADOR_CAMBIADO'
    );
  END IF;
END $$;

ALTER TYPE public.tipo_historial_subcampania
  ADD VALUE IF NOT EXISTS 'BORRADOR_CREADO';
ALTER TYPE public.tipo_historial_subcampania
  ADD VALUE IF NOT EXISTS 'SUBCAMPANIA_ACTIVADA';
ALTER TYPE public.tipo_historial_subcampania
  ADD VALUE IF NOT EXISTS 'SUBCAMPANIA_COMPLETADA';
ALTER TYPE public.tipo_historial_subcampania
  ADD VALUE IF NOT EXISTS 'SUBCAMPANIA_FINALIZADA_PARCIAL';
ALTER TYPE public.tipo_historial_subcampania
  ADD VALUE IF NOT EXISTS 'SUBCAMPANIA_CANCELADA';
ALTER TYPE public.tipo_historial_subcampania
  ADD VALUE IF NOT EXISTS 'TRANSICION_A_MONITOREO_HISTORICO';
ALTER TYPE public.tipo_historial_subcampania
  ADD VALUE IF NOT EXISTS 'EQUIPO_AMPLIADO';
ALTER TYPE public.tipo_historial_subcampania
  ADD VALUE IF NOT EXISTS 'EQUIPO_REDUCIDO';
ALTER TYPE public.tipo_historial_subcampania
  ADD VALUE IF NOT EXISTS 'COORDINADOR_CAMBIADO';

-- =====================================================================
-- 2. Tabla subcampania_historial (append-only)
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.subcampania_historial (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subcampania_id    BIGINT NOT NULL,
  tipo_historial    public.tipo_historial_subcampania NOT NULL,
  estado_origen     public.estado_subcampania,
  estado_destino    public.estado_subcampania,
  observaciones     TEXT,
  metadata          JSONB NOT NULL DEFAULT '{}'::jsonb,
  actor_user_id     BIGINT,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT subcampania_historial_subcampania_fk
    FOREIGN KEY (subcampania_id)
    REFERENCES public.subcampania (id)
    ON DELETE RESTRICT,

  CONSTRAINT subcampania_historial_actor_fk
    FOREIGN KEY (actor_user_id)
    REFERENCES public.usuario (id)
    ON DELETE SET NULL,

  CONSTRAINT subcampania_historial_metadata_object_chk
    CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX IF NOT EXISTS subcampania_historial_subcampania_idx
  ON public.subcampania_historial (subcampania_id);

CREATE INDEX IF NOT EXISTS subcampania_historial_subcampania_created_at_idx
  ON public.subcampania_historial (subcampania_id, created_at);

CREATE INDEX IF NOT EXISTS subcampania_historial_tipo_idx
  ON public.subcampania_historial (tipo_historial);

CREATE INDEX IF NOT EXISTS subcampania_historial_actor_idx
  ON public.subcampania_historial (actor_user_id);

COMMENT ON TABLE public.subcampania_historial IS
  'Historial append-only del ciclo de vida de la subcampania (RN-PLA-06/37, docs §4.1).';

-- Append-only: bloquear UPDATE/DELETE/TRUNCATE.
CREATE OR REPLACE FUNCTION public.fn_subcampania_historial_prevent_mutation()
RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION
    'public.subcampania_historial es append-only: no se permite %, solo INSERT.',
    TG_OP;
END $$;

DROP TRIGGER IF EXISTS subcampania_historial_prevent_mutation_trg
  ON public.subcampania_historial;

CREATE TRIGGER subcampania_historial_prevent_mutation_trg
  BEFORE UPDATE OR DELETE OR TRUNCATE ON public.subcampania_historial
  FOR EACH STATEMENT
  EXECUTE FUNCTION public.fn_subcampania_historial_prevent_mutation();

-- =====================================================================
-- 3. Tabla subcampania_meta_especie (plan por especie, RN-PLA-15..18)
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.subcampania_meta_especie (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subcampania_id      BIGINT NOT NULL,
  planta_id           BIGINT NOT NULL,
  porcentaje_objetivo NUMERIC(5,2) NOT NULL,
  cantidad_objetivo   INT NOT NULL,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by          BIGINT NOT NULL,
  updated_by          BIGINT NOT NULL,

  CONSTRAINT subcampania_meta_especie_subcampania_fk
    FOREIGN KEY (subcampania_id)
    REFERENCES public.subcampania (id)
    ON DELETE CASCADE,

  CONSTRAINT subcampania_meta_especie_planta_fk
    FOREIGN KEY (planta_id) REFERENCES public.planta (id),

  CONSTRAINT subcampania_meta_especie_created_by_fk
    FOREIGN KEY (created_by) REFERENCES public.usuario (id),
  CONSTRAINT subcampania_meta_especie_updated_by_fk
    FOREIGN KEY (updated_by) REFERENCES public.usuario (id),

  CONSTRAINT subcampania_meta_especie_uq
    UNIQUE (subcampania_id, planta_id),

  CONSTRAINT subcampania_meta_especie_porcentaje_chk
    CHECK (porcentaje_objetivo > 0 AND porcentaje_objetivo <= 100),

  CONSTRAINT subcampania_meta_especie_cantidad_chk
    CHECK (cantidad_objetivo > 0)
);

CREATE INDEX IF NOT EXISTS subcampania_meta_especie_subcampania_idx
  ON public.subcampania_meta_especie (subcampania_id);

CREATE INDEX IF NOT EXISTS subcampania_meta_especie_planta_idx
  ON public.subcampania_meta_especie (planta_id);

COMMENT ON TABLE public.subcampania_meta_especie IS
  'Plan por especie de la subcampania. En BORRADOR editable; al activar SUM(%)=100 y SUM(cantidad)=meta_total_arboles (RN-PLA-15/16).';

-- =====================================================================
-- 4. RPC fn_subcampania_cancelar (RN-PLA-37)
-- =====================================================================

CREATE OR REPLACE FUNCTION public.fn_subcampania_cancelar(
  p_id BIGINT,
  p_actor_user_id BIGINT,
  p_motivo TEXT
)
RETURNS public.subcampania
LANGUAGE plpgsql
AS $$
DECLARE
  v_sub public.subcampania%ROWTYPE;
  v_asignaciones_liberadas INT;
BEGIN
  IF p_motivo IS NULL OR btrim(p_motivo) = '' THEN
    RAISE EXCEPTION 'El motivo de cancelacion es obligatorio.'
      USING ERRCODE = 'P0001';
  END IF;

  -- Lock pesimista de la subcampania para evitar carreras con plantacion.
  SELECT *
  INTO v_sub
  FROM public.subcampania
  WHERE id = p_id
    AND deleted_at IS NULL
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Subcampania % no encontrada.', p_id
      USING ERRCODE = 'P0002';
  END IF;

  IF v_sub.estado NOT IN ('BORRADOR', 'ACTIVA') THEN
    RAISE EXCEPTION
      'Solo se puede cancelar una subcampania en BORRADOR o ACTIVA (estado actual: %).',
      v_sub.estado
      USING ERRCODE = 'P0001';
  END IF;

  IF COALESCE(v_sub.total_plantado_inicial, 0) > 0 THEN
    RAISE EXCEPTION
      'La subcampania ya tiene plantaciones registradas (total_plantado_inicial = %). Usar cierre FINALIZADA_PARCIAL.',
      v_sub.total_plantado_inicial
      USING ERRCODE = 'P0001';
  END IF;

  -- Bloquear asignaciones activas antes de liberarlas (evita carreras
  -- con nuevas reservas / devoluciones).
  PERFORM 1
  FROM public.asignacion_vivero_subcampania
  WHERE subcampania_id = p_id
    AND estado = 'ACTIVA'
  FOR UPDATE;

  -- Devolucion logica de todas las asignaciones activas. El trigger
  -- asignacion_vivero_subcampania_estado_trg pasara cada fila a 'DEVUELTA'.
  UPDATE public.asignacion_vivero_subcampania
     SET cantidad_devuelta =
         cantidad_devuelta + saldo_asignado_disponible
   WHERE subcampania_id = p_id
     AND estado = 'ACTIVA'
     AND saldo_asignado_disponible > 0;

  GET DIAGNOSTICS v_asignaciones_liberadas = ROW_COUNT;

  -- Marcar subcampania como CANCELADA. Inactivacion, no borrado fisico:
  -- se conserva la fila con deleted_at/deleted_by para trazabilidad.
  UPDATE public.subcampania
     SET estado      = 'CANCELADA',
         deleted_at  = NOW(),
         deleted_by  = p_actor_user_id,
         updated_at  = NOW(),
         updated_by  = p_actor_user_id
   WHERE id = p_id
  RETURNING * INTO v_sub;

  -- Registrar evento en historial.
  INSERT INTO public.subcampania_historial (
    subcampania_id,
    tipo_historial,
    estado_origen,
    estado_destino,
    observaciones,
    metadata,
    actor_user_id
  )
  VALUES (
    p_id,
    'SUBCAMPANIA_CANCELADA',
    -- estado_origen: leemos el previo a este UPDATE — no vive en v_sub tras el RETURNING,
    -- asi que lo dejamos en NULL y guardamos el detalle en metadata.
    NULL,
    'CANCELADA',
    p_motivo,
    jsonb_build_object(
      'asignaciones_liberadas', v_asignaciones_liberadas,
      'motivo_devolucion', 'CIERRE_SUBCAMPANIA'
    ),
    p_actor_user_id
  );

  RETURN v_sub;
END;
$$;

COMMENT ON FUNCTION public.fn_subcampania_cancelar(BIGINT, BIGINT, TEXT) IS
  'Cancela una subcampania sin plantaciones (RN-PLA-37): setea estado=CANCELADA, libera asignaciones activas como devolucion logica (sin evento M2, ver RN-VIV-48) y registra SUBCAMPANIA_CANCELADA en historial. Atomico.';

-- =====================================================================
-- 5. RPC fn_vivero_reservar_stock_lote — guard por proposito
-- =====================================================================
-- Actualiza el guard de 045: rechaza siempre BORRADOR y CANCELADA.
-- PLANTACION_INICIAL solo con subcampania ACTIVA.
-- REPOSICION con ACTIVA, COMPLETADA o FINALIZADA_PARCIAL (RN-PLA-12).

CREATE OR REPLACE FUNCTION public.fn_vivero_reservar_stock_lote(
  p_lote_vivero_id BIGINT,
  p_subcampania_id BIGINT,
  p_cantidad_asignada INT,
  p_proposito public.proposito_asignacion,
  p_usuario_asignacion_id BIGINT
)
RETURNS public.asignacion_vivero_subcampania
LANGUAGE plpgsql
AS $$
DECLARE
  v_lote public.lote_vivero%ROWTYPE;
  v_subcampania_estado public.estado_subcampania;
  v_saldo_reservado INT;
  v_saldo_disponible INT;
  v_asignacion public.asignacion_vivero_subcampania%ROWTYPE;
BEGIN
  IF p_cantidad_asignada IS NULL OR p_cantidad_asignada <= 0 THEN
    RAISE EXCEPTION 'No se puede reservar una cantidad menor o igual a 0.';
  END IF;

  SELECT *
  INTO v_lote
  FROM public.lote_vivero
  WHERE id = p_lote_vivero_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Lote de vivero % no encontrado.', p_lote_vivero_id;
  END IF;

  IF v_lote.estado_lote IS DISTINCT FROM 'ACTIVO' THEN
    RAISE EXCEPTION
      'No se puede reservar desde un lote en estado %.',
      v_lote.estado_lote;
  END IF;

  IF v_lote.saldo_vivo_actual IS NULL OR v_lote.saldo_vivo_actual <= 0 THEN
    RAISE EXCEPTION 'El lote % no tiene saldo vivo disponible.', p_lote_vivero_id;
  END IF;

  SELECT estado
  INTO v_subcampania_estado
  FROM public.subcampania
  WHERE id = p_subcampania_id
    AND deleted_at IS NULL
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Subcampania % no encontrada.', p_subcampania_id;
  END IF;

  -- Nunca se acepta reserva contra BORRADOR ni CANCELADA (RN-VIV-11 / RF-PLA-04).
  IF v_subcampania_estado IN ('BORRADOR', 'CANCELADA') THEN
    RAISE EXCEPTION
      'No se puede reservar para una subcampania en estado %. Solo se admite tras activar y siempre que no este cancelada.',
      v_subcampania_estado;
  END IF;

  -- Guard por proposito (RN-PLA-12).
  IF p_proposito = 'PLANTACION_INICIAL' AND v_subcampania_estado <> 'ACTIVA' THEN
    RAISE EXCEPTION
      'PLANTACION_INICIAL solo se permite con la subcampania en ACTIVA (estado actual: %).',
      v_subcampania_estado;
  END IF;

  IF p_proposito = 'REPOSICION'
     AND v_subcampania_estado NOT IN ('ACTIVA', 'COMPLETADA', 'FINALIZADA_PARCIAL') THEN
    RAISE EXCEPTION
      'REPOSICION solo se permite con la subcampania en ACTIVA, COMPLETADA o FINALIZADA_PARCIAL (estado actual: %).',
      v_subcampania_estado;
  END IF;

  PERFORM 1
  FROM public.asignacion_vivero_subcampania
  WHERE lote_vivero_id = p_lote_vivero_id
    AND estado = 'ACTIVA'
  FOR UPDATE;

  SELECT COALESCE(SUM(saldo_asignado_disponible), 0)::INT
  INTO v_saldo_reservado
  FROM public.asignacion_vivero_subcampania
  WHERE lote_vivero_id = p_lote_vivero_id
    AND estado = 'ACTIVA';

  v_saldo_disponible := v_lote.saldo_vivo_actual - v_saldo_reservado;

  IF p_cantidad_asignada > v_saldo_disponible THEN
    RAISE EXCEPTION
      'La cantidad solicitada (%) excede el saldo vivo disponible para asignacion del lote % (%).',
      p_cantidad_asignada,
      p_lote_vivero_id,
      v_saldo_disponible;
  END IF;

  INSERT INTO public.asignacion_vivero_subcampania (
    lote_vivero_id,
    subcampania_id,
    cantidad_asignada,
    proposito,
    usuario_asignacion_id
  )
  VALUES (
    p_lote_vivero_id,
    p_subcampania_id,
    p_cantidad_asignada,
    p_proposito,
    p_usuario_asignacion_id
  )
  RETURNING * INTO v_asignacion;

  RETURN v_asignacion;
END;
$$;

COMMENT ON FUNCTION public.fn_vivero_reservar_stock_lote(
  BIGINT,
  BIGINT,
  INT,
  public.proposito_asignacion,
  BIGINT
) IS
  'Reserva stock de un lote para una subcampania. Rechaza siempre BORRADOR y CANCELADA; PLANTACION_INICIAL requiere ACTIVA; REPOSICION admite ACTIVA/COMPLETADA/FINALIZADA_PARCIAL (RN-VIV-11, RN-PLA-12).';

NOTIFY pgrst, 'reload schema';
