-- Supabase / PostgreSQL
-- Crea el enum y la tabla de historial de Recolección.
-- Supone que ya existen:
--   public.recoleccion(id)
--   public.usuario(id)
--   public.estado_registro_recoleccion

do $$
begin
  if not exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where t.typname = 'tipo_historial_recoleccion'
      and n.nspname = 'public'
  ) then
    create type public.tipo_historial_recoleccion as enum (
      'BORRADOR_CREADO',
      'SOLICITUD_VALIDACION',
      'VALIDACION_APROBADA',
      'VALIDACION_RECHAZADA',
      'BORRADOR_ELIMINADO'
    );
  end if;
end
$$;

create table if not exists public.recoleccion_historial (
  id bigint generated by default as identity primary key,
  recoleccion_id bigint not null,
  tipo_historial public.tipo_historial_recoleccion not null,
  estado_origen public.estado_registro_recoleccion null,
  estado_destino public.estado_registro_recoleccion null,
  observaciones text null,
  metadata jsonb not null default '{}'::jsonb,
  actor_user_id bigint null,
  created_at timestamptz not null default now(),
  constraint recoleccion_historial_recoleccion_fk
    foreign key (recoleccion_id)
    references public.recoleccion (id)
    on delete restrict,
  constraint recoleccion_historial_actor_fk
    foreign key (actor_user_id)
    references public.usuario (id)
    on delete set null
);

create index if not exists idx_recoleccion_historial_recoleccion_id
  on public.recoleccion_historial (recoleccion_id);

create index if not exists idx_recoleccion_historial_created_at
  on public.recoleccion_historial (created_at);

create index if not exists idx_recoleccion_historial_tipo
  on public.recoleccion_historial (tipo_historial);

comment on table public.recoleccion_historial is
  'Historial append-only del ciclo de vida del registro de recoleccion.';

comment on column public.recoleccion_historial.tipo_historial is
  'Evento de ciclo de vida del registro; no se usa para movimientos de saldo.';

comment on column public.recoleccion_historial.metadata is
  'Datos adicionales del evento, sin reemplazar columnas estructuradas.';
